name: ssiw
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - click
  - ipython
  - pip
  - python>=3.10
  - matplotlib
  - pytorch-cuda
  - torchvision
  - pip:
      - black
      - flake8
      - isort
      - tqdm
      - livelossplot
      - mmcv
      - mmsegmentation
      - timm
      - gensim
      - pytorch-ignite
      - git+https://github.com/openai/CLIP.git
